//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilMedical
    {
        public int Id { get; set; }
        public string NamePacient { get; set; }
        public int IdUser { get; set; }
        public string Alergii { get; set; }
        public string Gen { get; set; }
        public string BoliCronice { get; set; }
        public string GrupaSanguina { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
