//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public int IdClinica { get; set; }
        public int IdUser { get; set; }
    
        public virtual Clinici Clinici { get; set; }
        public virtual Users Users { get; set; }
    }
}
